### PR TITLE
Replace markdown with HTML in HTML file.

### PR DESCRIPTION
**Pull request by kevinGC**
Addresses #56.

### CODE REVIEW

**Comment by amscanne** [comment]
This has always been .html, why has it stopped working now?

**Comment by ianlewis** [comment]
I broke it in this change: https://github.com/google/gvisor-website/commit/7853b971d43f773002ea92ecc95af7becd9dac55
The 'feature' blocks rendered as markdown before but they added a superfluous <p> so I changed it to render as is. 

I have a bit better idea about how to fix it which involves fixing the html for the feature block shortcode and will send a PR today. Probably needs to be fixed upstream to be fixed properly.

**Comment by ianlewis** [comment]
My alternative PR is here: https://github.com/google/gvisor-website/pull/58

**Comment by ianlewis** [comment]
@kevinGC Thanks for taking stab at this. Fixed this in #58 https://github.com/google/gvisor-website/commit/66cc254a8710cdaeb6e56bb45aec1e51f696660a

**Pull request closed without merging**
